[package]
name = "jmt"
version = "0.1.0"
authors = ["Penumbra Labs <team@penumbra.zone>", "Diem Association <opensource@diem.com>"]
description = "Jellyfish Merkle Tree (forked from Diem)"
repository = "https://github.com/penumbra-zone/jellyfish-merkle"
homepage = "https://penumbra.zone"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
async-recursion = "1"
byteorder = "1.4.3"
itertools = { version = "0.10.0", default-features = false }
mirai-annotations = "1.10.1"
num-derive = "0.3.3"
num-traits = "0.2.14"
once_cell = "1.7.2"
proptest = { version = "1.0.0", optional = true }
proptest-derive = { version = "0.3.0", optional = true }
rand = { version = "0.8.3" }
serde = { version = "1.0.124", features = ["derive"] }
thiserror = "1.0.24"
aes-gcm = "0.8.0"
bytes = "1.0.1"
chrono = { version = "0.4.19", default-features = false, features = ["clock"] }
hex = "0.4.3"
prometheus = "0.13"
serde_json = "1.0.64"
serde_bytes = "0.11.5"
serde-name = "0.2"
tiny-keccak = { version = "2.0.2", default-features = false, features = ["sha3"] }
bcs = "0.1.2"
futures = "0.3"
sha2 = "0.9.3"

[dev-dependencies]
rand = "0.8.3"
proptest = "1.0.0"
proptest-derive = "0.3.0"
tokio = { version = "1", features = ["full"] }