[package]
name = "jmt"
version = "0.1.0"
authors = ["Penumbra Labs <team@penumbra.zone>", "Diem Association <opensource@diem.com>"]
description = "Jellyfish Merkle Tree (forked from Diem)"
repository = "https://github.com/penumbra-zone/jellyfish-merkle"
homepage = "https://penumbra.zone"
license = "Apache-2.0"
publish = false
edition = "2018"

[features]
default = ["ics23"]

[dependencies]
ics23 = { version = "0.7" , optional = true }
anyhow = "1.0.38"
byteorder = "1.4.3"
itertools = { version = "0.10.0", default-features = false }
mirai-annotations = "1.10.1"
num-derive = "0.3.3"
num-traits = "0.2.14"
once_cell = "1.7.2"
proptest = { version = "1.0.0" }
proptest-derive = { version = "0.3.0"}
serde = { version = "1.0.124", features = ["derive"] }
thiserror = "1.0.24"
prometheus = "0.13"
bcs = "0.1.2"
sha2 = "0.10"

[dev-dependencies]
rand = { version = "0.8.3" }
